### ISSUE TITLE
Error importing selective_scan_cuda

### ISSUE THREAD

**Issue by alitinet** [helicalAI/helical#147]
Hi,

I'm having some trouble installing the package, namely I get this error after installing from main:

> from helical import Geneformer, GeneformerConfig
INFO:datasets:PyTorch version 2.3.0 available.
INFO:datasets:TensorFlow version 2.17.0 available.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre/groups/ml01/workspace/alitinet/mambaforge/envs/helical/lib/python3.11/site-packages/helical/__init__.py", line 37, in <module>
    from .models.helix_mrna import HelixmRNA, HelixmRNAConfig
  File "/lustre/groups/ml01/workspace/alitinet/mambaforge/envs/helical/lib/python3.11/site-packages/helical/models/helix_mrna/__init__.py", line 1, in <module>
    from .model import HelixmRNA
  File "/lustre/groups/ml01/workspace/alitinet/mambaforge/envs/helical/lib/python3.11/site-packages/helical/models/helix_mrna/model.py", line 5, in <module>
    from .modeling_helix_mrna import HelixmRNAPretrainedModel
  File "/lustre/groups/ml01/workspace/alitinet/mambaforge/envs/helical/lib/python3.11/site-packages/helical/models/helix_mrna/modeling_helix_mrna.py", line 50, in <module>
    if is_mamba_2_ssm_available():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/groups/ml01/workspace/alitinet/mambaforge/envs/helical/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 418, in is_mamba_2_ssm_available
    import mamba_ssm
  File "/lustre/groups/ml01/workspace/alitinet/mambaforge/envs/helical/lib/python3.11/site-packages/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/lustre/groups/ml01/workspace/alitinet/mambaforge/envs/helical/lib/python3.11/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 16, in <module>
    import selective_scan_cuda
ImportError: /lustre/groups/ml01/workspace/alitinet/mambaforge/envs/helical/lib/python3.11/site-packages/selective_scan_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN3c1021throwNullDataPtrErrorEv

As far as I understand it's an issue with finding compatible torch, mamba_ssm and causal_conv1d versions similar to [this issue](https://github.com/state-spaces/mamba/issues/169), but I haven't managed to find a combination that works so far. Could you help me with this? Thanks!

PS. The versions I have installed are

> causal-conv1d             1.4.0 
mamba-ssm                 2.2.2 
torch                     2.3.0                
torchtext                 0.18.0               
torchvision               0.18.0

**Comment by maxiallard** [comment]
Hi @alitinet , 
Thanks a lot for raising the issue!
Usually this happens when there is a mismatch between the cuda version and the torch version. One possibility is that when installing the different packages, your system reused cached packages.
Can you try the following:

```
pip uninstall torch torchtext torchaudio -y
pip install torch==2.3.0 torchtext torchaudio --index-url https://download.pytorch.org/whl/cu121
pip uninstall mamba-ssm causal-conv1d -y
pip install mamba-ssm==2.2.2 --no-cache-dir
pip install causal-conv1d== 1.4.0 --no-cache-dir
```
In the meantime, we are trying to simplify some of the dependencies for these packages.
Let me know if that works.

**Comment by alitinet** [comment]
Hi @maxiallard,

Thanks for your reply! Now I get this error when trying to install torch with `pip install torch==2.3.0 torchtext torchaudio --index-url https://download.pytorch.org/whl/cu121`:

> ERROR: Cannot install torch==2.3.0, torchtext==0.15.0+cpu, torchtext==0.15.1+cpu, torchtext==0.15.2+cpu, torchtext==0.16.0+cpu, torchtext==0.16.1+cpu, torchtext==0.16.2+cpu, torchtext==0.17.0+cpu, torchtext==0.5.0 and torchtext==0.6.0 because these package versions have conflicting dependencies.

**Comment by alitinet** [comment]
Ok, I think I managed to make it work! At least the imports don't throw any errors any more. What worked was
```
pip install torch==2.3.0 torchtext torchaudio
pip install mamba-ssm==2.2.2 --no-cache-dir
pip install causal-conv1d==1.4.0 --no-cache-dir
pip install git+https://github.com/helicalAI/helical.git --no-cache-dir
```

So I'm closing the issue for now, thank you!
